window.TREND_API_URL = "https://script.google.com/macros/s/AKfycbwGHOduL0BHvH-o4up9nbk1wYFi54D2KOnW1AFDigpBzyuAOTWzPfpSFPGSyFVj_fmTmg/exec";
window.EASYSTORE_VERSION = "ES7_BATCH25_FULL_ACCOUNTING_CORE";

window.EASYSTORE_AUTO_REFRESH = true;
window.EASYSTORE_DISABLE_PHONE_ACTIVATION = true;

// Batch 25
window.EASYSTORE_VERSION = "ES7_BATCH25_FULL_ACCOUNTING_CORE";
window.EASYSTORE_AUTO_REFRESH = true;
window.EASYSTORE_FULL_ACCOUNTING = true;
