
/*********************** EasyStore ES16 / V1859 - Accounting Manager Core ************************
  مدير حسابات مطبعجي - ES18 V1861:
  - إصلاح تفعيل/تعديل الأصناف والخامات.
  - مسح كل الخامات لضياء فقط مع نسخة احتياطية.
  - صفحة حسابات العملاء والموردين + خزنة + قفلة اليوم + سجل مراجعة.
  - تجهيز رسالة واتساب تلقائية/يدوية برابط فواتير العميل بعد تقفيل الفاتورة.
  - تحميل العميل في فاتورة المبيعات من قاعدة العملاء.
**********************************************************************************************/
(function(){
  'use strict';
  window.EASYSTORE_VERSION='ES18 V1861 Error Fix + Zero Reset';
  window.EASYSTORE_ES16_V1859_ACCOUNTING_MANAGER_CORE=true;
  window.EASYSTORE_ES17_V1860_UI_THEME=true;
  window.EASYSTORE_ES18_V1861_ERROR_FIX=true;
  var qs=new URLSearchParams(location.search);
  function $(id){return document.getElementById(id);} function txt(v){return String(v==null?'':v).replace(/\s+/g,' ').trim();}
  function norm(v){return txt(v).toLowerCase().replace(/[إأآا]/g,'ا').replace(/[ى]/g,'ي').replace(/[ةه]/g,'ه').replace(/[ؤ]/g,'و').replace(/[ئ]/g,'ي');}
  function num(v){var n=parseFloat(String(v||'').replace(/[٬,]/g,'.').replace(/[^0-9.\-]/g,''));return isFinite(n)?n:0;} function money(v){return (Math.round(num(v)*100)/100).toLocaleString('ar-EG')+' ج';}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m];});}
  function safeText(el){return txt(el && typeof el.textContent==='string' ? el.textContent : '');}
  function ctxText(el,n){return safeText(el).slice(0,n||400);}
  function isAccountingKitchenContext(el){var t=norm(ctxText(el.closest&&el.closest('section,.card,.content,main')||document.body,500));return /اصناف|الأصناف|الصنف|خامات|خامة|مطبخ|بنود|بند ثابت|مواد|item|material|kitchen/.test(t) && !/حساب العملاء|حسابات العملاء|كشف حساب|الخزنة|الموردين/.test(t);}
  function userData(){var hand={};try{hand=JSON.parse(localStorage.getItem('MATBAGY_EMPLOYEE_SSO')||'{}');}catch(e){}var hp=hand.params||{},hu=hand.user||{};return {name:qs.get('name')||qs.get('username')||hp.name||hp.username||hu.name||hu.username||'',username:qs.get('username')||qs.get('name')||hp.username||hp.name||hu.username||hu.name||'',token:qs.get('token')||hp.token||hu.token||'',mode:qs.get('mode')||hp.mode||'',department:qs.get('department')||hp.department||''};}
  function isAdmin(){var u=userData(),k=norm([u.name,u.username,u.mode,u.department].join(' '));return /ضياء|diaa|admin|full|kitchen/.test(k);} function isFinal(){var u=userData(),k=norm([u.name,u.username,u.mode,u.department].join(' '));return /رحمه|رحمة|rahma|ريفان|ريڤان|revan|rivan|final|ضياء|diaa|admin|full/.test(k);} 
  function api(action,data){return new Promise(function(resolve,reject){var base=txt(window.TREND_API_URL||'');if(!base){reject(new Error('TREND_API_URL missing'));return;}var cb='ES16_'+Date.now()+'_'+Math.floor(Math.random()*99999);var u=userData();var p=new URLSearchParams(Object.assign({action:action,callback:cb,username:u.username||u.name,name:u.name||u.username,token:u.token||'',_ts:Date.now()},data||{}));var s=document.createElement('script'),done=false;function clean(){if(done)return;done=true;try{delete window[cb];}catch(e){window[cb]=undefined;}if(s.parentNode)s.parentNode.removeChild(s);}window[cb]=function(r){clean();resolve(r||{});};s.onerror=function(){clean();reject(new Error('server'));};s.src=base+(base.indexOf('?')<0?'?':'&')+p.toString();document.body.appendChild(s);setTimeout(function(){if(!done){clean();reject(new Error('timeout'));}},25000);});}
  function toast(t,bad){var m=$('es16Msg')||$('mainMsg')||document.querySelector('.msg');if(m){m.textContent=t||'';m.classList.toggle('error',!!bad);m.classList.toggle('ok',!!t&&!bad);}else if(t){alert(t);}}
  var style=document.createElement('style');style.textContent='.es16-panel{background:#fff;border:1px solid #d8e4ea;border-radius:18px;padding:16px;margin:14px 0;box-shadow:0 10px 24px #0001}.es16-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.es16-grid .wide{grid-column:span 2}.es16-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.es16-table{width:100%;border-collapse:collapse;margin-top:12px}.es16-table th,.es16-table td{border:1px solid #e5edf5;padding:7px;text-align:right}.es16-btn{background:#eef6f5;color:#0f6f5c;border:1px solid #d2e8e4;border-radius:10px;padding:8px 11px;cursor:pointer;font-weight:800}.es16-btn.primary{background:#0f8a70;color:#fff;border-color:#0f8a70}.es16-btn.danger{background:#d64545;color:#fff;border-color:#d64545}.es16-version{position:fixed;left:10px;bottom:10px;z-index:9999;background:#111827;color:white;border-radius:999px;padding:6px 10px;font-size:11px}.hidden#clientInvoiceMenu,.hidden.clientInvoiceMenu,.hidden.client-invoice-menu{display:none!important}@media(max-width:900px){.es16-grid{grid-template-columns:1fr}.es16-grid .wide{grid-column:auto}}';document.head.appendChild(style);
  function versionBind(){document.title='إيزي ستور مطبعجي ES18 V1861';document.querySelectorAll('.version-badge,.version,.app-version').forEach(function(el){el.textContent='ES18 V1861 Error Fix';});if(!$('es16Version')){var v=document.createElement('div');v.id='es16Version';v.className='es16-version';v.textContent='ES18 V1861';document.body.appendChild(v);}}
  function closeInvoiceMenus(force){['clientInvoiceMenu','saCustomerDrop','customerInvoiceMenu','invoiceCustomerMenu'].forEach(function(id){var el=$(id);if(el){el.classList.add('hidden');el.style.display='none';el.setAttribute('aria-hidden','true');}});document.querySelectorAll('.clientInvoiceMenu,.client-invoice-menu,.dropdown-menu,.floating-menu,.invoice-menu,[data-invoice-menu]').forEach(function(el){var key=((el.id||'')+' '+(el.className||'')+' '+(el.textContent||'')).toLowerCase();if(force||/invoice|فاتورة|menu|dropdown/.test(key)){el.classList.add('hidden');el.style.display='none';el.setAttribute('aria-hidden','true');}});} 
  window.toggleClientInvoiceMenu=function(ev){if(ev){ev.preventDefault();ev.stopPropagation();}var m=$('clientInvoiceMenu')||document.querySelector('.clientInvoiceMenu,.client-invoice-menu,[data-invoice-menu]');if(!m)return false;var open=m.classList.contains('hidden')||m.style.display==='none'||getComputedStyle(m).display==='none';closeInvoiceMenus(true);if(open){m.classList.remove('hidden');m.style.display='block';m.setAttribute('aria-hidden','false');}return false;};['pointerdown','mousedown','click','touchstart','focusin'].forEach(function(evt){document.addEventListener(evt,function(ev){var t=ev.target;if(t&&t.closest&&t.closest('#clientInvoiceMenu,.clientInvoiceMenu,.client-invoice-menu,[data-invoice-menu],[onclick*="toggleClientInvoiceMenu"]'))return;closeInvoiceMenus(true);},true);});document.addEventListener('keydown',function(ev){if(ev.key==='Escape')closeInvoiceMenus(true);},true);window.addEventListener('scroll',function(){closeInvoiceMenus(true);},true);
  var customers=[];
  function partyName(r,type){return type==='supplier'?txt(r.name||r.supplierName||r.supplier||r['اسم المورد']||r['المورد']):txt(r.name||r.customerName||r.customer||r['اسم العميل']||r['اسم الشات / المكتب']);}
  async function loadCustomers(){try{var r=await api('getEasyStoreCustomers',{limit:1000});if(r.success)customers=r.customers||[];}catch(e){}}
  function bestCustomer(q){q=norm(q);if(!q||q.length<2)return null;var exact=null,start=null,contains=null;customers.forEach(function(r){var name=partyName(r,'customer'),phone=txt(r.phone||r.mobile||r.customerPhone||''),code=txt(r.code||r.customerCode||'');var blob=norm([name,phone,code].join(' '));if(norm(name)===q||norm(phone)===q||norm(code)===q)exact=r;else if(norm(name).indexOf(q)===0&&!start)start=r;else if(blob.indexOf(q)>=0&&!contains)contains=r;});return exact||start||contains;}
  function hydrateCustomerPickers(){document.querySelectorAll('input,select').forEach(function(el){if(el.dataset.es16CustomerPicker)return;var meta=norm([el.id,el.name,el.placeholder,el.getAttribute('aria-label')].join(' '));if(!/عميل|customer|client/.test(meta)||/مورد|supplier/.test(meta))return;el.dataset.es16CustomerPicker='1';el.addEventListener('change',function(){var r=bestCustomer(el.value);if(r)fillCustomer(el,r);});el.addEventListener('blur',function(){var r=bestCustomer(el.value);if(r)fillCustomer(el,r);});});}
  function fillCustomer(input,r){var scope=input.closest('form,.card,section,main')||document;var name=partyName(r,'customer');if(name)input.value=name;var phone=txt(r.phone||r.mobile||r.customerPhone||''),code=txt(r.code||r.customerCode||''),bal=num(r.currentBalance||r.balance||r.debt||r.remainingBalance);scope.querySelectorAll('input').forEach(function(el){var m=norm([el.id,el.name,el.placeholder,el.getAttribute('aria-label')].join(' '));if(code&&/كود|code/.test(m)&&!/اوردر|order/.test(m))el.value=code;if(phone&&/تليفون|هاتف|موبايل|phone|mobile/.test(m))el.value=phone;if(/مديونيه|مديونية|رصيد|balance|debt/.test(m))el.value=bal||'';});toast('تم تحميل العميل: '+name,false);}
  function rowInfo(btn){
    var tr=btn && btn.closest ? btn.closest('tr') : null;
    var tds=tr?Array.from(tr.children):[];
    var raw=tds.map(function(td){return txt(td.textContent);});
    var vals=raw.map(function(v){return v.replace(/تعديل\/مديونية|تعديل|إيقاف|ايقاف|تفعيل|حذف|إرسال|رابط|الفاتورة|كشف حساب|حساب المورد/g,'').trim();}).filter(Boolean);
    var ctx=(btn&&btn.closest&&btn.closest('section,.card,.content,main'))||document.body;
    var title=norm(ctxText(ctx,700));
    var kind=/خامات|خامة|مطبخ|material/.test(title)&&!/اصناف|الأصناف|البنود الثابتة/.test(title)?'material':'template';
    var dept=vals.find(function(v){return /طباعة|ليزر|مشترك|عام/.test(v);})||'';
    var name='';
    vals.some(function(v){
      var x=txt(v);
      if(!x) return false;
      if(/^(طباعة|ليزر|مشترك|عام|مفعل|موقوف|نعم|لا|ج|EGP)$/i.test(x)) return false;
      if(/^[-+]?\d+(\.\d+)?\s*(ج|egp)?$/i.test(x)) return false;
      if(/^(0|0 ج|0\.00 ج|—|-|\*)$/.test(x)) return false;
      name=x; return true;
    });
    if(!name){
      var rtxt=txt(tr&&tr.textContent||'').replace(/تعديل\/مديونية|تعديل|إيقاف|ايقاف|تفعيل|حذف/g,' ');
      name=txt(rtxt.split(/\n|\||—/).map(txt).find(Boolean)||'');
    }
    return {tr:tr,kind:kind,name:name,department:dept,vals:vals,raw:raw};
  }
  async function activateItem(btn,active){
    var r=rowInfo(btn);
    if(!r.name){toast('لم أتعرف على اسم الصنف من الصف. افتح التعديل أو أعد تحميل الصفحة.',true);return;}
    btn.disabled=true;
    try{
      var res=await api('activateAccountingItemV1859',{kind:r.kind,name:r.name,itemName:r.name,materialName:r.name,department:r.department,active:active?'نعم':'لا'});
      toast((res&&res.message)||'',!(res&&res.success));
      if(res&&res.success)setTimeout(function(){location.reload();},700);
    }catch(e){toast('خطأ اتصال بالسيرفر أثناء التفعيل: '+(e&&e.message?e.message:'راجع Apps Script'),true);}finally{btn.disabled=false;}
  }
  function ensureEditPanel(){if($('es16ItemEditPanel'))return;var host=document.querySelector('.content')||document.querySelector('main')||document.body;var p=document.createElement('section');p.id='es16ItemEditPanel';p.className='es16-panel hidden';p.innerHTML='<h3>تعديل الصنف / الخامة</h3><div id="es16Msg" class="msg"></div><div class="es16-grid"><input id="es16EditKind" type="hidden"><input id="es16OldName" type="hidden"><div class="wide"><label>الاسم</label><input id="es16EditName"></div><div><label>القسم</label><select id="es16EditDept"><option>طباعة</option><option>ليزر</option><option>مشترك</option><option>عام</option></select></div><div><label>التكلفة / سعر الوحدة</label><input id="es16EditCost" type="number"></div><div><label>سعر البيع</label><input id="es16EditSale" type="number"></div><div><label>العرض</label><input id="es16EditWidth" type="number"></div><div><label>الطول</label><input id="es16EditHeight" type="number"></div><div><label>الهالك %</label><input id="es16EditWaste" type="number"></div><div><label>الحالة</label><select id="es16EditActive"><option value="نعم">مفعل</option><option value="لا">موقوف</option></select></div><div class="wide"><label>ملاحظات</label><input id="es16EditNotes"></div></div><div class="es16-actions"><button id="es16SaveItemEdit" class="es16-btn primary">تحديث</button><button id="es16CancelItemEdit" class="es16-btn">إغلاق</button></div>';host.prepend(p);$('es16CancelItemEdit').onclick=function(){p.classList.add('hidden');};$('es16SaveItemEdit').onclick=saveItemEdit;}
  function openEdit(btn){ensureEditPanel();var r=rowInfo(btn);$('es16EditKind').value=r.kind;$('es16OldName').value=r.name;$('es16EditName').value=r.name;$('es16EditDept').value=r.department||'طباعة';$('es16EditCost').value='';$('es16EditSale').value='';$('es16EditWidth').value='';$('es16EditHeight').value='';$('es16EditWaste').value='';$('es16EditNotes').value='';$('es16ItemEditPanel').classList.remove('hidden');$('es16ItemEditPanel').scrollIntoView({behavior:'smooth',block:'start'});toast('تم تحميل بيانات الصف للتعديل. راجع الأسعار ثم اضغط تحديث.',false);}
  async function saveItemEdit(){try{var res=await api('updateAccountingItemV1859',{kind:$('es16EditKind').value,oldName:$('es16OldName').value,name:$('es16EditName').value,itemName:$('es16EditName').value,materialName:$('es16EditName').value,department:$('es16EditDept').value,cost:$('es16EditCost').value,unitCost:$('es16EditCost').value,salePrice:$('es16EditSale').value,width:$('es16EditWidth').value,height:$('es16EditHeight').value,waste:$('es16EditWaste').value,active:$('es16EditActive').value,notes:$('es16EditNotes').value});toast(res.message||'',!res.success);if(res.success)setTimeout(function(){location.reload();},800);}catch(e){toast('خطأ اتصال أثناء تحديث الصنف.',true);}}
  function bindItemButtons(){
    if(window.__ES18_ITEM_BUTTONS_BOUND__) return;
    window.__ES18_ITEM_BUTTONS_BOUND__=true;
    document.addEventListener('click',function(ev){
      var b=ev.target&&ev.target.closest&&ev.target.closest('button,a'); if(!b)return;
      var t=txt(b.textContent);
      var ctx=(b.closest&&b.closest('section,.card,.content,main'))||document.body;
      if(!isAccountingKitchenContext(b)) return;
      if(/^تفعيل$/.test(t)){ev.preventDefault();ev.stopPropagation();activateItem(b,true);return false;}
      if(/إيقاف|ايقاف/.test(t)){ev.preventDefault();ev.stopPropagation();activateItem(b,false);return false;}
      if(/^تعديل$/.test(t)){ev.preventDefault();ev.stopPropagation();openEdit(b);return false;}
    },true);
  }
  function ensureManagerPanel(){
    if($('es16ManagerPanel'))return;
    var host=document.querySelector('.content')||document.querySelector('main')||document.body;
    var p=document.createElement('section');
    p.id='es16ManagerPanel';
    p.className='es16-panel';
    p.innerHTML='<h3>مدير الحسابات ES18</h3><div id="es16Msg" class="msg"></div><div class="es16-actions"><button id="es16OpenLedger" class="es16-btn primary">حسابات العملاء والموردين</button><button id="es16OpenCashbox" class="es16-btn">الخزنة والتحصيلات</button><button id="es16OpenDayClose" class="es16-btn">قفلة اليوم</button><button id="es16OpenAudit" class="es16-btn">سجل المراجعة</button><button id="es16OpenZeroReset" class="es16-btn danger">تهيئة لوضع الصفر</button></div><div id="es16ManagerContent"></div>';
    host.prepend(p);
    $('es16OpenLedger').onclick=renderLedger;
    $('es16OpenCashbox').onclick=renderCashbox;
    $('es16OpenDayClose').onclick=renderDayClose;
    $('es16OpenAudit').onclick=loadAudit;
    $('es16OpenZeroReset').onclick=renderZeroReset;
  }
  function renderLedger(){var c=$('es16ManagerContent');c.innerHTML='<div class="es16-panel"><h3>حركة حساب عميل / مورد</h3><div class="es16-grid"><div><label>نوع الحساب</label><select id="es16PartyType"><option value="customer">عميل</option><option value="supplier">مورد</option></select></div><div class="wide"><label>الاسم</label><input id="es16PartyName" placeholder="اكتب اسم العميل أو المورد"></div><div><label>العملية</label><select id="es16LedgerOp"><option value="opening_debt">مديونية افتتاحية</option><option value="payment_received">سداد عميل</option><option value="invoice">فاتورة عميل</option><option value="purchase_invoice">فاتورة مورد</option><option value="payment_paid">دفعة لمورد</option><option value="adjustment_plus">تسوية زيادة</option><option value="adjustment_minus">تسوية نقص</option></select></div><div><label>المبلغ</label><input id="es16LedgerAmount" type="number"></div><div><label>طريقة الدفع</label><select id="es16LedgerMethod"><option>نقدي</option><option>فودافون كاش</option><option>إنستا باي</option><option>تحويل بنكي</option><option>تسوية</option></select></div><div><label>مرجع</label><input id="es16LedgerRef"></div><div class="wide"><label>ملاحظات</label><input id="es16LedgerNotes"></div></div><div class="es16-actions"><button id="es16SaveLedger" class="es16-btn primary">حفظ وتحديث الرصيد</button><button id="es16LoadLedger" class="es16-btn">عرض الكشف</button></div><div id="es16LedgerHistory"></div></div>';$('es16SaveLedger').onclick=saveLedger;$('es16LoadLedger').onclick=loadLedger;}
  async function saveLedger(){if(!isFinal()){toast('هذه الحركة عند ضياء / رحمه / ريفان فقط.',true);return;}try{var r=await api('savePartyLedgerTransaction',{partyType:$('es16PartyType').value,partyName:$('es16PartyName').value,operation:$('es16LedgerOp').value,amount:$('es16LedgerAmount').value,paymentMethod:$('es16LedgerMethod').value,refNo:$('es16LedgerRef').value,notes:$('es16LedgerNotes').value});toast(r.message||'',!r.success);if(r.success)loadLedger();}catch(e){toast('تعذر حفظ الحركة.',true);}}
  async function loadLedger(){try{var r=await api('getPartyAccountV1858',{partyType:$('es16PartyType').value,partyName:$('es16PartyName').value});if(!r.success){toast(r.message,true);return;}var rows=r.transactions||[];$('es16LedgerHistory').innerHTML='<h4>الرصيد الحالي: '+money(r.balance)+'</h4>'+(rows.length?'<table class="es16-table"><thead><tr><th>التاريخ</th><th>العملية</th><th>المبلغ</th><th>الرصيد بعد</th><th>ملاحظات</th></tr></thead><tbody>'+rows.slice().reverse().map(function(x){return '<tr><td>'+esc(x.createdAt||'')+'</td><td>'+esc(x.operationLabel||x.operation||'')+'</td><td>'+money(x.amount)+'</td><td>'+money(x.balanceAfter)+'</td><td>'+esc(x.notes||'')+'</td></tr>';}).join('')+'</tbody></table>':'لا توجد حركات.');}catch(e){toast('تعذر تحميل الكشف.',true);}}
  function renderCashbox(){var c=$('es16ManagerContent');c.innerHTML='<div class="es16-panel"><h3>الخزنة والتحصيلات</h3><div class="es16-grid"><div><label>نوع الحركة</label><select id="es16CashType"><option value="receipt">قبض من عميل</option><option value="supplier_payment">دفع لمورد</option><option value="expense">مصروف</option><option value="transfer">تحويل</option></select></div><div class="wide"><label>الطرف</label><input id="es16CashParty"></div><div><label>المبلغ</label><input id="es16CashAmount" type="number"></div><div><label>طريقة الدفع</label><select id="es16CashMethod"><option>نقدي</option><option>فودافون كاش</option><option>إنستا باي</option><option>تحويل بنكي</option></select></div><div><label>الخزنة</label><input id="es16Cashbox" value="الخزنة الرئيسية"></div><div><label>مرجع</label><input id="es16CashRef"></div><div class="wide"><label>ملاحظات</label><input id="es16CashNotes"></div></div><div class="es16-actions"><button id="es16SaveCash" class="es16-btn primary">حفظ حركة الخزنة</button><button id="es16LoadCash" class="es16-btn">عرض حركات الخزنة</button></div><div id="es16CashHistory"></div></div>';$('es16SaveCash').onclick=saveCashbox;$('es16LoadCash').onclick=loadCashbox;}
  async function saveCashbox(){try{var r=await api('saveCashboxTransactionV1859',{type:$('es16CashType').value,partyName:$('es16CashParty').value,amount:$('es16CashAmount').value,paymentMethod:$('es16CashMethod').value,cashbox:$('es16Cashbox').value,refNo:$('es16CashRef').value,notes:$('es16CashNotes').value});toast(r.message||'',!r.success);if(r.success)loadCashbox();}catch(e){toast('تعذر حفظ حركة الخزنة.',true);}}
  async function loadCashbox(){try{var r=await api('getCashboxTransactionsV1859',{});if(!r.success){toast(r.message,true);return;}var rows=r.rows||[];$('es16CashHistory').innerHTML=rows.length?'<table class="es16-table"><thead><tr><th>التاريخ</th><th>نوع</th><th>طرف</th><th>مبلغ</th><th>دفع</th><th>بواسطة</th></tr></thead><tbody>'+rows.slice().reverse().map(function(x){return '<tr><td>'+esc(x.createdAt||x["وقت التسجيل"]||'')+'</td><td>'+esc(x.type||x["نوع الحركة"]||'')+'</td><td>'+esc(x.party||x["الطرف"]||'')+'</td><td>'+money(x.amount||x["المبلغ"])+'</td><td>'+esc(x.paymentMethod||x["طريقة الدفع"]||'')+'</td><td>'+esc(x.createdBy||x["مسجل بواسطة"]||'')+'</td></tr>';}).join('')+'</tbody></table>':'لا توجد حركات.';}catch(e){toast('تعذر تحميل الخزنة.',true);}}
  function renderDayClose(){var c=$('es16ManagerContent');c.innerHTML='<div class="es16-panel"><h3>قفلة اليوم</h3><div class="es16-grid"><div><label>التاريخ</label><input id="es16DayDate" type="date"></div><div><label>رصيد فعلي</label><input id="es16ActualBalance" type="number"></div><div class="wide"><label>ملاحظات</label><input id="es16DayNotes"></div></div><div class="es16-actions"><button id="es16CloseDayBtn" class="es16-btn primary">حفظ قفلة اليوم</button></div><div id="es16DayResult"></div></div>';try{$('es16DayDate').value=new Date().toISOString().slice(0,10);}catch(e){}$('es16CloseDayBtn').onclick=closeDay;}
  async function closeDay(){try{var r=await api('closeDayV1859',{date:$('es16DayDate').value,actualBalance:$('es16ActualBalance').value,notes:$('es16DayNotes').value});toast(r.message||'',!r.success);if(r.success){var s=r.summary||{};$('es16DayResult').innerHTML='<div class="es16-panel"><b>قبض: '+money(s.receipts)+'</b> — دفع: '+money(s.payments)+' — مصروفات: '+money(s.expenses)+' — فرق: '+money(s.diff)+'</div>';}}catch(e){toast('تعذر قفل اليوم.',true);}}
  async function loadAudit(){var c=$('es16ManagerContent');c.innerHTML='<div class="es16-panel"><h3>سجل المراجعة</h3><div id="es16AuditRows">جاري التحميل...</div></div>';try{var r=await api('getAuditLogV1859',{});if(!r.success){$('es16AuditRows').innerHTML=esc(r.message||'تعذر التحميل');return;}var rows=r.rows||[];$('es16AuditRows').innerHTML=rows.length?'<table class="es16-table"><thead><tr><th>وقت</th><th>مستخدم</th><th>عملية</th><th>كيان</th><th>مرجع</th><th>ملاحظات</th></tr></thead><tbody>'+rows.slice().reverse().map(function(x){return '<tr><td>'+esc(x.createdAt||x["وقت التسجيل"]||'')+'</td><td>'+esc(x.user||x["المستخدم"]||'')+'</td><td>'+esc(x.operation||x["نوع العملية"]||'')+'</td><td>'+esc(x.entity||x["الكيان"]||'')+'</td><td>'+esc(x.refNo||x["رقم المرجع"]||'')+'</td><td>'+esc(x.notes||x["ملاحظات"]||'')+'</td></tr>';}).join('')+'</tbody></table>':'لا توجد عمليات.';}catch(e){$('es16AuditRows').innerHTML='تعذر التحميل.';}}
  function renderZeroReset(){
    var c=$('es16ManagerContent');
    c.innerHTML='<div class="es16-panel" style="border-color:#fecaca;background:#fff7f7"><h3>تهيئة لوضع الصفر</h3><p><b>سيتم إنشاء نسخة احتياطية ثم مسح بيانات الحسابات والتشغيل فقط.</b></p><p>سيتم مسح الخامات، الأصناف، مكونات الصنف، المخزون، الفواتير، فواتير الأقسام، الهوالك، الخزنة، قفلات اليوم، وكشف حساب العملاء والموردين. <b>لن يتم مسح العملاء ولا المستخدمين.</b></p><label>اكتب بالضبط: تهيئة لوضع الصفر</label><input id="es16ZeroConfirm" placeholder="تهيئة لوضع الصفر"><div class="es16-actions"><button id="es16ZeroResetBtn" class="es16-btn danger">تنفيذ التهيئة الآن</button></div></div>';
    $('es16ZeroResetBtn').onclick=zeroReset;
  }
  async function zeroReset(){
    if(!isAdmin()){toast('تهيئة وضع الصفر عند ضياء فقط.',true);return;}
    if(txt($('es16ZeroConfirm').value)!=='تهيئة لوضع الصفر'){toast('اكتب التأكيد كما هو: تهيئة لوضع الصفر',true);return;}
    try{
      var r=await api('resetAccountingToZeroV1861',{confirm:'تهيئة لوضع الصفر'});
      toast((r&&r.message)||'',!(r&&r.success));
      if(r&&r.success){setTimeout(function(){location.reload();},1200);}
    }catch(e){toast('تعذر تنفيذ التهيئة: '+(e&&e.message?e.message:'راجع Apps Script'),true);}
  }
  function sendInvoiceReview(customer, invoiceNo, total, paid, remaining){api('createInvoiceReviewMessageV1859',{customerName:customer,invoiceNo:invoiceNo,total:total,paid:paid,remaining:remaining}).then(function(r){if(!r.success){toast(r.message,true);return;}try{navigator.clipboard&&navigator.clipboard.writeText(r.text||'');}catch(e){} if(r.whatsappUrl) window.open(r.whatsappUrl,'Matbagy_Invoice_Review'); toast('تم تجهيز رسالة مراجعة الفاتورة ونسخها.',false);}).catch(function(){toast('تعذر تجهيز رسالة مراجعة الفاتورة.',true);});}
  function installInvoiceReviewButtons(){document.querySelectorAll('tr,.invoice-row,.sale-row').forEach(function(row){if(row.dataset.es16ReviewBtn)return;var text=norm(row.textContent||'');if(!/فاتورة|عميل|مدفوع|باقي|الباقي/.test(text))return;row.dataset.es16ReviewBtn='1';var b=document.createElement('button');b.type='button';b.className='es16-btn';b.textContent='إرسال رابط الفاتورة';b.onclick=function(ev){ev.preventDefault();ev.stopPropagation();var raw=txt(row.textContent);var customer=(raw.match(/عميل[:：]?\s*([^\n\|]+)/)||[])[1]||'';sendInvoiceReview(customer,'','','','');};var cell=document.createElement(row.tagName==='TR'?'td':'div');cell.appendChild(b);row.appendChild(cell);});}
  function bind(){versionBind();loadCustomers();hydrateCustomerPickers();bindItemButtons();ensureManagerPanel();installInvoiceReviewButtons();closeInvoiceMenus(true);}document.addEventListener('DOMContentLoaded',bind);setTimeout(bind,300);setTimeout(bind,1500);setInterval(function(){versionBind();hydrateCustomerPickers();installInvoiceReviewButtons();},4000);
})();
